server:
  port: 8080

spring:
  datasource:
  #    url: jdbc:h2:file:./DB
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  batch:
    job:
      enabled: false
